### PR TITLE
fix: Avoid printing an extra newline when exporting resources

### LINKED ISSUE #3593: `--export` results at times in double newline at EOF
While looking into #3592, I noticed some of our tests around `--export` functionalities have files which end with a double newline.

The culprit of this seems to be the usage of `rootCmd.Println` to print the rendered YAML, which by itself adds a newline (even if the thing it prints already has this at the end).

To provide a better UX, we should ensure we only print a single one at the end of the file which also makes

```console
$ flux ... --export >> file.yaml
$ flux ... --export >> file.yaml
```

produce prettier files.

### PR DESCRIPTION
**Pull request by yiannistri**
Closes #3593 

Following Hidde's hint, the change in this PR should prevent extra newlines from being printed. This affects both the `flux export ..` command and the `--export` flag used in other Flux commands.

Also tested with
```
flux export .. >> export.yaml
flux export .. >> export.yaml
```
and it no longer produces a newline between resources in the same file.

### CODE REVIEW

File: cmd/flux/export.go [hunk 1]
```diff
@@ -115,7 +115,7 @@ func printExport(export interface{}) error {
 		return err
 	}
 	rootCmd.Println("---")
-	rootCmd.Println(resourceToString(data))
+	rootCmd.Print(resourceToString(data))
```
Comment (hiddeco) [inline cmd/flux/export.go:118]: Seeing this together with `resourceToString`, it might actually be better to add a `data = bytes.TrimSpace(data)` to the function below and keep this in place.

This would simply ensure that even if the generating function makes a mistake (by either forgetting to add a newline, or adding to many). We always return just a single newline at the end.

**Review by hiddeco — COMMENTED** [review]
Thanks a lot for picking this up :bow: 

Small suggestion based on second thoughts...

File: cmd/flux/export.go (hunk 1 above)
Comment (yiannistri) [reply cmd/flux/export.go]: Great suggestion 👍

**Review by hiddeco — APPROVED** [review]
Thank you @yiannistri :1st_place_medal:
