### PR TITLE
Extend `--team` flag to include access level

### LINKED ISSUE #1452: "flux bootstrap github" lowers existing "Admin" role of a GitHub team
### Describe the bug

If you have an existing GitHub repository in which a team—say, _engineering_—is granted [the maximal "Admin" role](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization#permission-levels-for-repositories-owned-by-an-organization), and you run _flux bootstrap github_ with the `--team` flag's value including this _engineering_ team, the command succeeds, but it lowers the nominated team's role to "Maintain."

### To Reproduce

1. Create a GitHub repository—say, _sample-repo_.
1. Grant a GitHub team—say, _engineering_—the "Admin" role in that repository.
1. Run a command like the following:
```shell
flux bootstrap github \
  --owner=sample-org \
  --repository=sample-repo \
  --team=engineering
```
1. In the GitHub Web UI, inspect the settings for the _sample-repo_ repository.  
  In the "Manage access" area, note that the _engineering_ team is still present, but now its role is only "Maintain" instead of its original "Admin" role.

### Expected behavior

If a nominated team already has at least the "Maintain" role in the repository, _flux bootstrap github_ should leave the team's entry as it was.

### Additional context

- Kubernetes version: 1.19.9
- Git provider: GitHub
- Container registry provider: Docker Hub

Below please provide the output of the following commands:

<details>
<summary>flux tool output</summary>

```cli
% flux --version
flux version 0.14.0

% flux check
► checking prerequisites
✔ kubectl 1.21.1 >=1.18.0-0
✔ Kubernetes 1.19.9 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.10.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.12.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.14.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.13.0
✔ all checks passed

% kubectl -n flux-system get all
NAME                                           READY   STATUS    RESTARTS   AGE
pod/helm-controller-85bfd4959d-9sgzz           1/1     Running   0          26m
pod/kustomize-controller-5687758989-nqr5d      1/1     Running   1          26m
pod/notification-controller-758d759586-zgkgs   1/1     Running   0          26m
pod/source-controller-85cd58f569-5xgnc         1/1     Running   0          26m

NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/notification-controller   ClusterIP   100.65.113.231   <none>        80/TCP    4h3m
service/source-controller         ClusterIP   100.70.153.192   <none>        80/TCP    4h3m
service/webhook-receiver          ClusterIP   100.65.156.205   <none>        80/TCP    4h3m

NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/helm-controller           1/1     1            1           4h3m
deployment.apps/kustomize-controller      1/1     1            1           4h3m
deployment.apps/notification-controller   1/1     1            1           4h3m
deployment.apps/source-controller         1/1     1            1           4h3m

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/helm-controller-85bfd4959d           1         1         1       4h3m
replicaset.apps/kustomize-controller-5687758989      1         1         1       4h3m
replicaset.apps/notification-controller-758d759586   1         1         1       4h3m
replicaset.apps/source-controller-85cd58f569         1         1         1       4h3m

[Logs elided.]
```
</details>

### PR DESCRIPTION
**Pull request by SomtochiAma**
Fixes #1452 
This pull request doesn't reconcile a team if the team already exists and the reconcile flag wasn't passed in. 
It also adds a feature where a user can specify the level of access that can be given to a team through the `--team` flag. It maintains backwards compatibility by defaulting to maintainer access if no access level is specified.

Example
`flux bootstrap github --team=eng:admin` -> Gives eng team admin access
`flux bootstrap github --team=eng` -> Gives eng team maintainer access

### CODE REVIEW

File: cmd/flux/bootstrap.go [hunk 1]
```diff
@@ -173,7 +174,12 @@ func bootstrapValidate() error {
 func mapTeamSlice(s []string, defaultPermission string) map[string]string {
 	m := make(map[string]string, len(s))
 	for _, v := range s {
-		m[v] = defaultPermission
+		if s := strings.Split(v, ":"); len(s) == 2 {
+			m[s[0]] = s[1]
+		} else {
+			m[v] = defaultPermission
+		}
 	}
```
Comment (hiddeco) [inline cmd/flux/bootstrap.go:182]:
```suggestion
		m[v] = defaultPermission
		if s := strings.Split(v, ":"); len(s) == 2 {
			m[v] = s[1]
		}
	}
```

Comment (hiddeco) [reply cmd/flux/bootstrap.go]: You did not include the `m[v]` suggestion within your new commit. Using the same value origin everywhere makes it both easier to refactor things in the future, and easier to identify what value is set.

**Review by hiddeco — APPROVED** [review]
Nice tiny addition with great powers, thanks @SomtochiAma. :1st_place_medal: 

If you smash your commits together, this can be merged.

**Comment by seh** [comment]
Thank you for coming back to #1452.
