### PR TITLE
Shorten Git SHA commit in `flux get` commands output

### LINKED ISSUE #2186: flux get kustomizations revision short commit sha instead full commit sha
### Describe the bug

When you have a small monitor and when you call `flux get kustomizations`
it shows `MESSAGE` and `REVISION` columns which contain `branch_name/full_sha` that is pretty long and does not fit to a single row, it is a bit harder when you have errors in specific customizations.

### Steps to reproduce

1. `flux get kustomizations`
2. check MESSAGE and REVISION columns it is very long.
```
NAME                          	READY	MESSAGE                                                                                                                            	REVISION                                                     	SUSPENDED
alb-ingress-controller        	True 	Applied revision: immediate-deployment/a40d363e5270cea36d0743d9fedaa5dd7a567dc5                                                    	immediate-deployment/a40d363e5270cea36d0743d9fedaa5dd7a567dc5	False
```

### Expected behavior

it should show like that
```                                                                                                                          	
alb-ingress-controller   True 	Applied revision: immediate-deployment/a40d363    immediate-deployment/a40d363	False
```

### Screenshots and recordings

image

### OS / Distro

macOS 12.0.1

### Flux version

flux version 0.17.2

### Flux check

N/A

### Git provider

Github

### Container Registry provider

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SomtochiAma**
This pull request shortens the sha1 commit hash from the status of Kustomization and GitRepository custom resource to the first seven digits when displaying output for `flux get kustomization` and `flux get source git`.

Fixes #2186 

Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

### CODE REVIEW

File: cmd/flux/get_kustomization.go [hunk 1]
```diff
@@ -94,3 +95,14 @@ func (a kustomizationListAdapter) statusSelectorMatches(i int, conditionType, co
 	item := a.Items[i]
 	return statusMatches(conditionType, conditionStatus, item.Status.Conditions)
 }
+
+
+func shortenCommitSha(msg string) string {
+	r := regexp.MustCompile("/([a-f0-9]{40})")
```
Comment (stefanprodan) [inline cmd/flux/get_kustomization.go:101]: We need to match the end of the message with `$`.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @SomtochiAma
