### PR TITLE
fix: normalize path for Windows compatibility

### LINKED ISSUE #5673: `flux build kustomization` fails on Windows
### Describe the bug

`flux build kustomization` fails on Windows when using a `--path` other than `.`. On Linux, all invocations with `.`, a relative path or an absolute path for `--path` succeed and correctly render the manifests.

### Steps to reproduce

1. Create a local folder `test` with a `kustomization.yaml`
    ```apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    
    resources:
    - test.yaml
    ```
2. Create `test.yaml` in the `test` folder with some test manifest like:
    ```apiVersion: v1
    kind: Pod
    metadata:
      name: test-pod
      namespace: default
    spec:
      containers:
      - name: test-container
        image: nginx:latest
    ```
3. Create a `test.yaml` with:
    ```apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: test
      namespace: default
    ```
4. `cd` into the test folder on Windows and run `flux build kustomization test --namespace default --kustomization-file ..\test.yaml --path . --dry-run`
5. The commands succeeds and prints the pod manifest
6. `cd ..` and then `flux build kustomization test --namespace default --kustomization-file .\test.yaml --path .\test\ --dry-run`
7. Observe the error `✗ failed to generate kustomization.yaml: failed to save original kustomization.yaml: open test\test\kustomization.yaml.original: The system cannot find the path specified. <nil> <nil>`
8. Run `flux build kustomization test --namespace default --kustomization-file C:\<absolute-path>\test.yaml --path C:\<absolute-path>\test\ --dry-run`
9. Observe the error `✗ failed to generate kustomization.yaml: failed to save original kustomization.yaml: open C:\<absolute-path>\test\C:\<absolute-path>\test\kustomization.yaml.original: The filename, directory name, or volume label syntax is incorrect. <nil> <nil>`

### Expected behavior

All invocations with `.`, a relative path or an absolute path return the rendered manifest

### Screenshots and recordings

_No response_

### OS / Distro

Windows 11

### Flux version

v2.7.5

### Flux check

N/A

### Git provider

_No response_

### Container Registry provider

_No response_

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sibasispadhi**
This commit fixes issue #5673 where 'flux build kustomization' fails on Windows when using --path with relative or absolute paths.

The bug manifested as duplicate path components:
  C:\path\test\C:\path\test\kustomization.yaml.original

Root cause: The path argument was passed directly without normalization, causing issues in downstream path joining.

Fix: Normalize the path using filepath.Abs() and filepath.Clean() before passing it to the builder. This ensures:
  - Relative paths are converted to absolute paths
  - Windows path separators are handled correctly
  - Path components are cleaned and deduplicated

Added unit tests to verify path normalization works correctly on both Linux and Windows platforms.

Fixes #5673

### CODE REVIEW

**Comment by stefanprodan** [comment]
Please run `make fmt` and force push.

File: cmd/flux/build_kustomization_path_test.go
Comment (matheuscscp) [inline cmd/flux/build_kustomization_path_test.go:1]: I don't see why create a new file here, we can just use the one we already have

File: cmd/flux/build_kustomization_path_test.go [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+		{
+			name:    "relative path",
+			input:   "test/path",
+			wantAbs: true,
+			wantErr: false,
+		},
+	}
+
+	// Only run Windows-specific tests on Windows
+	if runtime.GOOS == "windows" {
```
Comment (matheuscscp) [inline cmd/flux/build_kustomization_path_test.go]: Not sure how much value these tests have, not sure we have CI running on Windows or if any maintainers use Windows to develop. Maybe equivalent tests that just assert the usage of `filepath.Clean(filepath.Abs())` would be better, regardless of Windows, if possible

Comment (sibasispadhi) [reply cmd/flux/build_kustomization_path_test.go]: updated.

File: cmd/flux/build_kustomization_test.go [hunk 2]
```diff
@@ -218,3 +218,48 @@ spec:
...
+
+			// Verify the result is an absolute path
+			if !filepath.IsAbs(cleanPath) {
+				t.Errorf("Expected absolute path, got %q", cleanPath)
+			}
+
+			// Verify Clean doesn't break the path
+			if cleanPath == "" {
+				t.Errorf("filepath.Clean() returned empty path")
+			}
```
Comment (matheuscscp) [inline cmd/flux/build_kustomization_test.go]: The tests should be testing the Flux code, not the Go standard llibrary `filepath`

Comment (sibasispadhi) [reply cmd/flux/build_kustomization_test.go]: Got it. Updated. please take a look.

File: cmd/flux/build_kustomization_test.go [hunk 3]
```diff
@@ -218,3 +218,53 @@ spec:
...
+	}{
+		{
+			name:       "build with relative path",
+			args:       "build kustomization podinfo --path testdata/build-kustomization/podinfo",
+			resultFile: "./testdata/build-kustomization/podinfo-result.yaml",
+			assertFunc: "assertGoldenTemplateFile",
+		},
+		{
+			name:       "build with dot-slash relative path",
+			args:       "build kustomization podinfo --path ./testdata/build-kustomization/podinfo",
```
Comment (matheuscscp) [inline cmd/flux/build_kustomization_test.go]: These paths are too simple and don't test what's changing here. The initial paths from Windows seemed much better in  that regard. Maybe we can adapt them to Linux paths?

P.S.: The vibe-coding is wasting a bit of my time :upside_down_face:

Comment (sibasispadhi) [reply cmd/flux/build_kustomization_test.go]: Yeah, future is vibe coding. It will get used to soon. Let me recheck & get back.

Comment (sibasispadhi) [reply cmd/flux/build_kustomization_test.go]: Updated. please take a look when possible. The git should be integrated with a code reviewer agent, thats flush out initial issues before going to actual reviewers. That will save time. I am sure CNCF & other teams would be already thinking about it as that is the the vibe coding future. Have fixed it again, please take a look when possible :) . This time my code-assistant said, you will be happy & sorry :). Lets see !!  :--)

Comment (sibasispadhi) [reply cmd/flux/build_kustomization_test.go]: Or, are you suggesting to take out the test case all together ?

**Comment by matheuscscp** [comment]
Please squash, this PR should have a single commit

**Comment by sibasispadhi** [comment]
thank you for the review, @matheuscscp .done

**Review by matheuscscp — APPROVED** [review]
LGTM

File: cmd/flux/build_kustomization_test.go (hunk 3 above)
Comment (matheuscscp) [reply cmd/flux/build_kustomization_test.go]: Using AI effectively and with other people's time in mind is good. Vibe-coding is not.
