### PR TITLE
diff: Take into account the server-side inventory for local Flux Kustomizations

### LINKED ISSUE #3733: flux diff ks doesn't list removed resources
### Describe the bug

`flux diff ks` only lists drifted and created resources. I'd expect removed resources to be listed as well. Optionally with configurable behavior regarding `.spec.prune` (warn, ignore, etc).

### Steps to reproduce

1. On an existing install, remove a resource (either by removing a file or removing a reference from `kustomization.yaml`).
2. Run `flux diff ks ...`
3. No changes are listed

### Expected behavior

The removed resource(s) to be listed as such.

### Screenshots and recordings

_No response_

### OS / Distro

N/A

### Flux version

v0.41.2

### Flux check

► checking prerequisites
✔ Kubernetes 1.24.9-gke.3200 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.31.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.31.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.26.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.35.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.33.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.36.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta2
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta2
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1beta2
✔ all checks passed

### Git provider

_No response_

### Container Registry provider

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by souleb**
fix #3733

If implemented users will be able to use `flux diff ks --kustomization-file` while retrieving the inventory from the cluster to report stale objects. This implies that a local Flux Kustomization file takes precedence over it's live counterpart.

For `flux build ks --kustomization-file`, the cluster will be not queried when using `--dry-run`.

### CODE REVIEW

File: internal/build/diff.go [hunk 1]
```diff
@@ -140,6 +140,9 @@ func (b *Builder) Diff() (string, bool, error) {
 			if err != nil {
 				return "", createdOrDrifted, err
 			}
+			if len(diffObjects) > 0 {
```
Comment (stefanprodan) [inline internal/build/diff.go:143]: Let’s rename diffObjects to staleObjects

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @souleb 🏅
