### PR TITLE
Maintain original scheme when using --token-auth

### LINKED ISSUE #3116: --allow-insecure-http forces HTTPS in corresponding GitRepository
### Describe the bug

Given an HTTP-based "dumb" Git server
When I try to bootstrap it with `flux bootstrap git --allow-insecure-http --token-auth --password XXX --url http://git.server --path x/y/z`
Then the URL in the `GitRepository` source created for it starts with HTTPS anyway
  And `Kustomize` fails to reconcile (if HTTPS is not configured on the "dumb" Git server)

### Steps to reproduce

1. Install Flux as normal.
2. Provision a Kind cluster
3. Create a HTTP-based Git server with nginx as documented [here](https://thenewstack.io/how-to-set-up-the-http-git-server-for-private-projects/)
4. Run: `flux bootstrap git --allow-insecure-http=true --url=http://git.server/test/repo --username=git --password=supersecret --path="x/y/z" --token-auth`
5. `kubectl -n flux-system get gitrepository`; inspect the URL

### Expected behavior

The URL should start with `http`

### Screenshots and recordings

_No response_

### OS / Distro

N/A

### Flux version

v0.33.0

### Flux check

N/A

### Git provider

Plain `git`

### Container Registry provider

N/A

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by carlosonunez-vmw**
Fixes #3116.

If you're using an HTTP-based Git server with Flux, you need to provide `--token-auth` to avoid triggering an SSH host key check (see [#2825](https://github.com/fluxcd/flux2/issues/2825#issuecomment-1151355914)). Unfortunately, doing this forces the URL in the `GitRepository` resource created during bootstrapping to always use `https`. This will cause Kustomization reconcile errors for servers that do not have HTTPS enabled or do not have the appropriate certs installed or available.

This pull request fixes this by keeping the repository URL scheme intact when using `--token-auth`.

Signed-off-by: Carlos Nunez <75340335+carlosonunez-vmw@users.noreply.github.com>

### CODE REVIEW

File: cmd/flux/bootstrap_git.go [hunk 1]
```diff
@@ -192,7 +192,7 @@ func bootstrapGitCmdRun(cmd *cobra.Command, args []string) error {
 
 		// Configure repository URL to match auth config for sync.
 		repositoryURL.User = nil
-		repositoryURL.Scheme = "https"
+		repositoryURL.Scheme = repositoryURL.Scheme
```
Comment (hiddeco) [inline cmd/flux/bootstrap_git.go:195]:
```suggestion
		if !bootstrapArgs.insecureHttpAllowed {
			repositoryURL.Scheme = "https"
		}
```

would probably be a better fix, to not blindly allow sending credentials over an insecure connection.

**Comment by carlosonunez-vmw** [comment]
Thanks, @hiddeco! Good suggestion.

**Comment by stefanprodan** [comment]
@carlosonunez-vmw please squash the two commits

**Review by hiddeco — APPROVED** [review]

**Comment by carlosonunez-vmw** [comment]
sorry for the delay; done.

**Comment by carlosonunez-vmw** [comment]
done; @stefanprodan PTAL

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @carlosonunez-vmw 🥇

**Comment by carlosonunez-vmw** [comment]
you're welcome!-- CarlosOn Sep 28, 2022, at 00:36, Stefan Prodan ***@***.***> wrote:﻿
@stefanprodan approved this pull request.

LGTM
Thanks @carlosonunez-vmw 🥇
