### PR TITLE
Check for multiple files in KUBECONFIG variable

### LINKED ISSUE #637: flux bootstrap KUBECONFIG with multiple config files error
I have `$KUBECONFIG` set to multiple files. This works with `flux check` as fixed for #472 but it does not work with `flux bootstrap` in flux cli version 0.5.7. See error below. I previously raised an issue for this in #300 which was fixed so I guess this could be a regression?

```
❯ flux bootstrap github \
  --owner=jonaskello \
  --repository=fleet-infra \
  --branch=main \
  --path=staging-cluster \
  --personal
► connecting to github.com
✔ repository created
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in flux-system namespace
error: stat /Users/JonKel/.kube/config:/Users/JonKel/.other/config.yml:/Users/JonKel/moreconfig.yml:/Users/JonKel/Downloads/yet-another-config.yaml: no such file or directory
✗ install failed
```

### PR DESCRIPTION
**Pull request by SomtochiAma**
Fixes #637 
Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

### CODE REVIEW

File: internal/utils/utils.go [hunk 1]
```diff
@@ -67,7 +67,7 @@ const (
 func ExecKubectlCommand(ctx context.Context, mode ExecMode, kubeConfigPath string, kubeContext string, args ...string) (string, error) {
 	var stdoutBuf, stderrBuf bytes.Buffer
 
-	if kubeConfigPath != "" {
+	if kubeConfigPath != "" && !containsMultipleConfigFiles(kubeConfigPath){
```
Comment (hiddeco) [inline internal/utils/utils.go:70]: (While not chimed in on details on why we pass an additional config to `kubectl` here)

You likely want to make use of [`filepath.SplitList`](https://golang.org/pkg/path/filepath/#SplitList) and simply check the `len`, as this already deals with `runtime.GOOS` / multi-path strings for you.

**Review by stefanprodan — APPROVED** [review]
LGTM

Please rebase with main
