### PR TITLE
Use provided SSH hostname to sync with SSH

### LINKED ISSUE #2207: Bootstrapping Bitbucket Server always uses port 22
### Describe the bug

When bootstrapping the latest flux (v0.24.1) to a BitBucket 6.10 server
```
flux bootstrap bitbucket-server \
  --owner=foo.user \
  --repository=flux-infra \
  --branch=main \
  --path=clusters/valhalla \
  --ssh-hostname='stash.company.com:7999' \
  --hostname=stash.company.com \
  --personal
```

The logs for the deployed source-controller show that the git clone fails because it is trying to connect to our server on port 22 and not port 7999.

```
{"level":"info","ts":"2021-12-12T15:42:02.590Z","logger":"controller.helmchart","msg":"Starting workers","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","worker count":2}
{"level":"error","ts":"2021-12-12T15:44:24.170Z","logger":"controller.gitrepository","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"GitRepository","name":"flux-system","namespace":"flux-system","error":"unable to clone 'ssh://git@stash.company.com/~foo.user/flux-infra': dial tcp 12.34.56.78:22: connect: connection timed out"}
```

It should be trying to clone from `ssh://git@stash.company.com:7999/~foo.user/flux-infra`

### Steps to reproduce

1. Execute the following to a server on a non-standard ssh port
```
flux bootstrap bitbucket-server \
  --owner=foo.user \
  --repository=flux-infra \
  --branch=main \
  --path=clusters/valhalla \
  --ssh-hostname='stash.company.com:7999' \
  --hostname=stash.company.com \
  --personal
```
2. Watch the logs for the sorce-controller pod after it comes up.

### Expected behavior

A successful post bootstrap sync.

### Screenshots and recordings

_No response_

### OS / Distro

macOS 11.6

### Flux version

v0.24.1

### Flux check

flux check
► checking prerequisites
✔ Kubernetes 1.21.2-eks-06eac09 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.2
✔ all checks passed

### Git provider

BitBucket Server 6.10

### Container Registry provider

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by souleb**
Signed-off-by: Soule BA <soule@weave.works>

Fixes #2207

### CODE REVIEW

**Comment by wpbeckwith** [comment]
I have validated that the PR fixes the bootstrap issue and allows flux's source-controller to successfully clone.

File: internal/bootstrap/bootstrap_provider.go [hunk 1]
```diff
@@ -200,6 +200,18 @@ func (b *GitProviderBootstrapper) ReconcileSyncConfig(ctx context.Context, optio
 		if err != nil {
 			return err
 		}
+
+		//take the sync URL and replace the hostname with the ssh hostname
+		if gitprovider.TransportType(b.syncTransportType) == gitprovider.TransportTypeSSH && b.sshHostname != "" {
```
Comment (hiddeco) [inline internal/bootstrap/bootstrap_provider.go:205]: How is the logic here different from what's being done on L438? And/or how can we incorporate it into this method so that we keep things contained?

Comment (souleb) [reply internal/bootstrap/bootstrap_provider.go:205]: The difference is on the transport type check:

`gitprovider.TransportType(b.syncTransportType)` vs `gitprovider.TransportType(b.bootstrapTransportType)`.

The check here seems at the right place as the func is  `ReconcileSyncConfig`

Comment (hiddeco) [reply internal/bootstrap/bootstrap_provider.go:205]: The difference (or why this is required) is because of the logic in `getCloneURL` which does an early return:

```go
	cloner, ok := repository.(gitprovider.CloneableURL); ok {
		return cloner.GetCloneURL("", transport), nil
	}
```

Given this (and as discussed in private) it would be better to change the logic there to ensure the if case is traversed, to save us from a headache in the future.

File: internal/bootstrap/bootstrap_provider.go [hunk 2]
```diff
@@ -414,14 +416,15 @@ func (b *GitProviderBootstrapper) getOrganization(ctx context.Context, subOrgs [
 func (b *GitProviderBootstrapper) getCloneURL(repository gitprovider.UserRepository, transport gitprovider.TransportType) (string, error) {
 	var url string
 	if cloner, ok := repository.(gitprovider.CloneableURL); ok {
-		return cloner.GetCloneURL("", transport), nil
+		url = cloner.GetCloneURL("", transport)
+	} else {
+		url = repository.Repository().GetCloneURL(transport)
+		// TODO(hidde): https://github.com/fluxcd/go-git-providers/issues/55
```
Comment (stefanprodan) [inline internal/bootstrap/bootstrap_provider.go:422]: This has been solved, so I think we no longer need the trim prefix.

**Comment by stefanprodan** [comment]
@souleb please rebase

**Review by hiddeco — APPROVED** [review]
